version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "5100:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: npm run dev -- --host 0.0.0.0
